:/#!/bin/csh
setenv LM_LICENSE_FILE 5280@172.16.201.225
setenv CDS_Netlisting_Mode "Analog"
setenv CDS_LIC_FILE $LM_LICENSE_FILE
setenv LANG en_US
#setenv CDS_LIC_FILE 5279@iiitbcad
setenv QRC_EXTRACTION_ENABLE
setenv ALTOS_64 1
setenv CDS_AUTO_64BIT NONE
setenv ASSURA_USE_PVS_LICENSE
setenv CDSHOME /mnt/cadence_tools/IC618
setenv OA_HOME /mnt/cadence_tools/IC618/oa_v22.60.086
#setenv OA_HOME /mnt/oa
set path=($path ${CDSHOME}/bin ${CDSHOME}/share/bin ${CDSHOME}/tools.lnx86/bin/64bit/ ${CDSHOME}/tools/bin ${CDSHOME}/share/dfII/bin ${CDSHOME}/tools.lnx86/dfII/bin ${CDSHOME}/tools/dfII/bin)
#setenv CDSHOME ~/cadence/installs/IC618
#set path = $CDSHOME/bin $CDSHOME/tools/bin $CDSHOME/tools/dfII/bin $CDSHOME/share/bin $path

#setenv LM_LICENSE_FILE 1717@172.16.201.90
setenv LD_PRELOAD /usr/lib64/libssl.so.1.0.2k:/usr/lib64/libcrypto.so.1.0.2k
#setenv MGLS_LICENSE_FILE 1717@172.16.201.90

setenv FLEXLM_DIAGNOSTICS 3
#setenv CDSHOME /home/CAD/Cadence_Installs/IC618

setenv CALIBRE_HOME  /mnt/cadence_tools/Mentor_tools/calibre/aoi_cal_2021.1_16.10
setenv LD_PRELOAD /usr/lib64/libssl.so.1.0.2k:/usr/lib64/libcrypto.so.1.0.2k
set path = ( $CALIBRE_HOME/bin $path )


setenv XRUN_HOME /mnt/cadence_tools/XCELIUM
setenv MVSHOME /mnt/cadence_tools/MVS
setenv MODUSHOME /mnt/cadence_tools/MODUS
setenv GENUSHOME //mnt/cadence_tools/GENUS211
setenv INNOVUSHOME /mnt/cadence_tools/INNOVUS
setenv QRC_HOME /mnt/cadence_tools/QUANTUS
setenv PVSHOME /mnt/cadence_tools/pvs
setenv PEAHOME /mnt/cadence_tools/PEGASUS
setenv SIGRITYHOME /mnt/cadence_tools/SIGRITY
setenv SPBHOME /mnt/cadence_tools/SPB
setenv SPECTRE /mnt/cadence_tools/SPECTRE
setenv SSVHOME /mnt/cadence_tools/ssv
setenv VMANAGER_HOME /mnt/cadence_tools/VMANAGER
setenv PAS //mnt/cadence_tools/PAS31
setenv JSPRHOME /mnt/cadence_tools/JASPER2012/jasper_2020.12




setenv LECHOME /mnt/cadence_tools/CONFRML211

#setenv SSVHOME /mnt/cadence_tools/ssv171/Install

#setenv SIGRITYHOME /mnt/cadence_tools/SIGRITY2017/Install



set path = ($SPBHOME/bin $SPBHOME/share/bin $SPBHOME/tools.lnx86/pcb/bin $SPBHOME/tools.lnx86/bin $path)

set path = ($CDSHOME/bin $CDSHOME/tools/bin $CDSHOME/tools/dfII/bin $CDSHOME/share/bin $path)

set path = ($QRC_HOME/bin $path)


#set path = ($MMSIMHOME/tools/bin $MMSIMHOME/tools/dfII/bin $MMSIMHOME/bin $MMSIMHOME/share/bin $path)

#set path = ($XHOME/bin $XHOME/tools/bin $XHOME/tools/dfII/bin $XHOME/share/bin $XHOME/tools.lnx86/bin $path)

set path=($path ${XRUN_HOME}/bin ${XRUN_HOME}/share/bin ${XRUN_HOME}/tools.lnx86/bin ${XRUN_HOME}/tools/bin ${XRUN_HOME}/share/dfII/bin ${XRUN_HOME}/tools.lnx86/dfII/bin ${XRUN_HOME}/tools/dfII/bin)

set path = ($SPECTRE/bin $SPECTRE/tools/bin $SPECTRE/tools/dfII/bin $SPECTRE/share/bin $path) 

set path = ($GENUSHOME/bin $GENUSHOME/share/bin $GENUSHOME/tools/dfII/bin $GENUSHOME/tools.lnx86/dfII/bin $GENUSHOME/tools/bin $path)
 
set path = ($PVSHOME/bin $PVSHOME/share/bin $PVSHOME/tools.lnx86/dfII/bin $path)

set path = ($INNOVUSHOME/bin $INNOVUSHOME/tools/bin $INNOVUSHOME/tools/dfII/bin $INNOVUSHOME/share/bin $path)

set path = ($LECHOME/bin $LECHOME/tools/bin $LECHOME/tools/dfII/bin $LECHOME/tools.lnx86/dfII/bin $LECHOME/tools.lnx86/dfII/bin $LECHOME/share/bin $path)

set path = ($SSVHOME/bin $SSVHOME/tools/bin $SSVHOME/tools/dfII/bin $SSVHOME/share/bin $path)

set path = ($SIGRITYHOME/bin $SIGRITYHOME/tools/bin $SIGRITYHOME/tools/dfII/bin $SIGRITYHOME/share/bin $path)

#set path = ($RCHOME/bin $RCHOME/share/bin $RCHOME/tools.lnx86/dfII/bin $RCHOME/tools.lnx86/bin $path)

set path = ($JSPRHOME/bin $JSPRHOME/share/bin $JSPRHOME/tools.lnx86/dfII/bin $JSPRHOME/tools.lnx86/bin $path)


#set path = ($STRATUSHOME/bin $STRATUSHOME/share/bin $STRATUSHOME/tools.lnx86/dfII/bin $STRATUSHOME/tools.lnx86/bin $path)

set path = ($SSVHOME/bin $SSVHOME/share/bin $SSVHOME/tools.lnx86/dfII/bin $SSVHOME/tools.lnx86/bin $path)

set path=($path ${VMANAGER_HOME}/bin ${VMANAGER_HOME}/share/bin ${VMANAGER_HOME}/tools.lnx86/bin ${VMANAGER_HOME}/tools/bin ${VMANAGER_HOME}/share/dfII/bin ${VMANAGER_HOME}/tools.lnx86/dfII/bin ${VMANAGER_HOME}/tools/dfII/bin)
#set path = ($CDSHOME/bin $CDSHOME/tools/bin $CDSHOME/tools/dfII/bin $CDSHOME/share/bin $path)


echo "                                     "
echo "*************************************"
echo "*****  Welcome to Cadence tools  ****"
echo "*************************************"
echo "                                     "
alias c clear
alias pdf evince
alias l ls


